export const DEFAULT_WELCOME: string = 'Default Welcome Intent'
export const GET_X: string = 'getX'
export const BYE: string = 'bye'
export const NOTIFICATION_RESPONSE: string = 'notification_response'
export const SETUP_PUSH: string = 'setup_push'
export const FINISH_SETUP_PUSH: string = 'finish_push_setup'
export const DELETE: string = 'delete'